# Generated by Django 5.0.4 on 2024-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
