# Generated by Django 5.0.4 on 2024-05-11 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_duration', models.DurationField(editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClimbedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('grade', models.CharField(max_length=10)),
                ('route_name', models.CharField(max_length=100)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='training.training')),
            ],
        ),
    ]
