# Generated by Django 5.0.4 on 2024-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbedroutetrainingsession',
            name='timeSection_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climbedroutetrainingsession',
            name='timeSection_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climbedroutetrainingsession',
            name='timeSection_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climbedroutetrainingsession',
            name='timeSection_4',
            field=models.IntegerField(default=0),
        ),
    ]
